# Generated by Django 5.1.6 on 2025-02-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_cepmodel_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cepmodel',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cepmodel',
            name='regiao',
        ),
    ]
